#!/bin/bash
set -e

source $(dirname $0)/version
source $(dirname $0)/images

cd $(dirname $0)/..

DIST=$(pwd)/dist/artifacts

pushd images/output
build_all "$@"
mkdir -p ${DIST}
copy_all ${DIST} "$@"
popd

mkdir -p ./build
ID=$(podman create ${REPO}/k3os-package:${TAG})
podman cp ${ID}:/output/k3os ./build/
podman rm -fv $ID

podman build \
  --build-arg ARCH=${ARCH} \
  --build-arg REPO=${REPO} \
  --build-arg TAG=${TAG} \
  --build-arg VERSION=${VERSION} \
  --file package/Containerfile \
  --tag ${REPO}/k3os:${TAG} \
  --tag ${REPO}/k3os:latest \
.
podman image save --output ./dist/images.tar \
  ${REPO}/k3os:${TAG} \
  ${REPO}/k3os:latest
echo ${REPO}/k3os:${TAG} > ./dist/images.txt
echo Built ${REPO}/k3os:${TAG}
