#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p build

bash -x ./scripts/build

ID=$(podman run --net=host --privileged --rm -itd $REPO/k3os-iso:$VERSION)
podman attach $ID || podman kill $ID
