#!/bin/bash

ARCH="amd64"
REGISTRY="ghcr.io"
USERNAME="sentinelos"
REGISTRY_AND_USERNAME="${REGISTRY}/${USERNAME}"

GIT_COMMIT=$(git describe --match=none --always --abbrev=8 --dirty)
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    VERSION="${GIT_COMMIT}"
else
    VERSION="${GIT_TAG}"
fi
