FROM alpine:3.16 as installer

ARG ARCH=amd64
ARG GROUP=sentinelos
ARG GROUP_ID=1001
ARG USER=sentinelos
ARG USER_ID=1001
ARG VERSION=
ARG WORKDIR=/app

RUN set -eux; \
    apk update; \
    apk add --no-cache \
        bash \
        bash-completion \
        bind-tools \
        bzip2 \
        ca-certificates \
        coreutils \
        curl \
        git \
        gzip \
        htop \
        jq \
        micro \
        nano \
        openssh-client \
        sudo \
        tar \
        tree \
        tzdata; \
    addgroup -g "${GROUP_ID}" -S "${GROUP}"; \
	adduser \
	    --disabled-password \
	    -g "${GROUP_ID}" \
	    -D \
        -S \
	    -s "/bin/bash" \
	    -h "/home/$USER" \
	    -u "${USER_ID}" \
	    -G "${GROUP}" "${USER}"; \
	mkdir -p "${WORKDIR}"; \
	chown -R "${USER}:${GROUP}" "${WORKDIR}"

COPY overlay /

RUN sed -i "s/{{VERSION}}/${VERSION}/" /etc/os-release; \
    rm -rf \
        /var/cache/apk/*

FROM scratch as final

ARG ARCH=amd64
ARG VERSION=
ARG WORKDIR=/app

ENV PS1="\@ \u@\h \w$ "
ENV EDITOR="nano"

LABEL org.opencontainers.image.authors="Sentinel OS Authors"
LABEL org.opencontainers.image.description="Sentinel OS Base Image"
LABEL org.opencontainers.image.licenses="MPL-2.0"
LABEL org.opencontainers.image.source="https://github.com/sentinelos/base"
LABEL org.opencontainers.image.title="Sentinel OS"

COPY --from=installer /  /

WORKDIR "${WORKDIR}"
CMD ["bash"]
